### PR TITLE
Upgrade brial to 1.2.3

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
Should boost be pinned?

**Comment by saraedum** [comment]
That was the wrong idea…

**Comment by saraedum** [comment]
I'll try to figure out what's the problem tomorrow…

**Comment by saraedum** [comment]
I don't really understand what is going on. Somehow `$BOOST_LDFLAGS` is empty and therefore boost unit test checks can not find the library to link against.

**Comment by saraedum** [comment]
@isuruf Have you seen that before?

**Comment by isuruf** [comment]
https://github.com/BRiAl/BRiAl/pull/25

**Comment by kiwifb** [comment]
Bother I thought `--with-boost-libdir` would help but no. Going back to the failure it looks like we don't use the right type in the tests with clang on OS X. The value returned by the tests are all way smaller than what is expected. I suspect there is a mix up between double and long double.

**Comment by kiwifb** [comment]
OK this is strange. The results we are looking at are supposed to be different for boost 1.62 and over. We are getting the results for boost versions lower than 1.62. I guess that what @isuruf wanted to ensure when pushing `--with-boost-libdir` in case we are picking up a system library.

**Comment by saraedum** [comment]
@kiwifb The `--with-boost-libdir` was just so that `configure` would find the boost library for the unit test framework. I don't think that as related to the failing tests on OSX at all. The conda packages are built on a mostly clean environment. There would be no system libraries to pick up, so that's certainly not what this was about.

**Comment by kiwifb** [comment]
I think there is a distinct possibility that the test results are just different on OS X (+clang) from what they are on linux. Although why they would be at the value of boost<1.62 is a bit beyond me.

**Comment by saraedum** [comment]
@kiwifb What do you mean?

**Comment by kiwifb** [comment]
@saraedum getting travis to work properly. I guess I would like my .travis.yml to be audited by someone else who has more expertise. I think I just fixed the bit that was annoying me in https://github.com/BRiAl/BRiAl/pull/25 (other than the failing test on OS X) but still it would be nice to have some review.

**Comment by isuruf** [comment]
Upgrade to 1.2.2 now that it's released?

**Comment by saraedum** [comment]
Sure. Let's see if OSX really works now…

**Comment by kiwifb** [comment]
Those are all new to me. Which version of boost is used?

**Comment by kiwifb** [comment]
I only tested as far as boost-1.65.1. I will have to do some new round of testing and figure if it is clang or libcxx. Looking at the code I would say I find the original output suspect. One of my big issues is that I don't know what should be correct.

**Comment by saraedum** [comment]
I am trying to understand what is going on. I don't believe the following theory really, but this is what I got:

The first failing test basically does
```
order_type order;
BoolePolyRing::block_iterator start(order.blockBegin()),finish(order.blockEnd());
```
and it expects `start != finish` to be false.

Resolving the types (not sure about `idx_type`,) the code snippet translates to
```
DegLexOrder order;
std::vector<idx_type>::const_iterator start(order.blockBegin()), finish(order.blockEnd());
```

Now `blockBegin()` and `blockEnd()` come from `COrderingBase` which implements both as
```
virtual block_iterator blockBegin() const { return block_iterator(); }
virtual block_iterator blockEnd() const { return block_iterator(); }
```
(`blockBegin` and `blockEnd` don't seem to be overriden in a relevant subclass.)

So, both are unitialized iterators (on a vector) if I am not mistaken.

In `libstdc++` unitialized iterators compare equal. Not sure what happens with the clang libraries.

The standard (or this [SO answer](https://stackoverflow.com/a/49059538/812379)) seems to say that the result of comparing with unitialized iterators is undefined.

**Comment by kiwifb** [comment]
So the current test rely on a GNUism. That wouldn't be a first since I started with clang. That means the test in its current form is crap and should just be removed.

**Comment by saraedum** [comment]
No, I don't think the test is wrong. Morally, the implementation of `blockBegin` and `blockEnd` is wrong. Let me try a different implementation…

**Comment by saraedum** [comment]
```
Running 122 test cases...
*** No errors detected
```
:)

**Comment by saraedum** [comment]
I'll create a PR upstream.

**Comment by saraedum** [comment]
There is going to be a 1.2.4 release very soon. We should wait for that.

**Comment by kiwifb** [comment]
Release published.

**Comment by isuruf** [comment]
Thanks @saraedum and @kiwifb

**Pull request merged**
